name: CI/CD Pipeline for Authentication Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      auth-mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: auth_DB
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppassword" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn clean
        mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/auth_DB?useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: admin

    - name: Build Docker Image for Authentication Service
      run: docker build -t authentication-service:latest .

    - name: Run Authentication Service Docker Container
      run: |
        docker network create auth-network
        docker run --network auth-network --name authentication_service -e SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/auth_DB?useSSL=false -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=admin -d -p 8082:8082 authentication-service:latest

